// Canonical procurement contract. The admin copy is generated by sync-procurement-contract.mjs.
export interface EvidenceLine { productId: string; skuId: string; quantity: number }
export interface SellerGroup { sellerId: string; lines: EvidenceLine[] }
export interface SupplierOrder {
  orderId: string;
  purchaseCnyMinor: number;
  lines: EvidenceLine[];
  payment: {
    state: "Unpaid" | "Dispatching" | "Paid" | "Review";
    idempotencyKey?: string;
    requestId?: string;
    paidAt?: string;
    settledAmountMinor?: number;
    settledCurrency?: string;
  };
}
export interface ProcurementManifest {
  version: 1;
  expectedTotalCnyMinor: number;
  sellers: SellerGroup[];
  orders: SupplierOrder[];
}
export interface OperationData {
  approvedFingerprint?: string;
  orderContentsIdentity?: string;
  createOrderList?: unknown[];
  approvedManifestIdentity?: string;
  dispatchToken?: string;
  kind: "create" | "pay";
  actor: string;
  actorName?: string;
  requestedAt: string;
  updatedAt: string;
  supplierId?: string; // Compatibility/display only; never evidence of complete procurement.
  supplierIds?: string[];
  requestId?: string;
  previewRequestId?: string;
  previewTotalCnyMinor?: number;
  purchaseLines?: Array<{ id: string; spec_id?: string; quantity: number }>;
  manifest?: ProcurementManifest;
  paidAt?: string;
  nextCheckAt?: string;
  message?: string;
  synced?: boolean;
  notification?: "Pending" | "Sending" | "Sent" | "Unknown" | "Skipped";
  legacy?: boolean;
}
function positiveMinor(value: number): boolean { return Number.isSafeInteger(value) && value > 0; }
function lineTotals(lines: EvidenceLine[]): string {
  if (!Array.isArray(lines) || !lines.length) throw new Error("Supplier item coverage is missing.");
  const totals = new Map<string, number>();
  for (const line of lines) {
    if (!line || typeof line.productId !== "string" || !line.productId.trim() ||
        typeof line.skuId !== "string" || !line.skuId.trim() || !positiveMinor(line.quantity))
      throw new Error("Supplier item identity or quantity is invalid.");
    const key = JSON.stringify([line.productId, line.skuId]);
    const quantity = (totals.get(key) ?? 0) + line.quantity;
    if (!Number.isSafeInteger(quantity)) throw new Error("Supplier quantity exceeds safe bounds.");
    totals.set(key, quantity);
  }
  return JSON.stringify([...totals].sort(([a], [b]) => a.localeCompare(b)));
}
export function assertCompleteManifest(manifest: ProcurementManifest | undefined): asserts manifest is ProcurementManifest {
  if (!manifest || manifest.version !== 1 || !positiveMinor(manifest.expectedTotalCnyMinor) ||
      !Array.isArray(manifest.sellers) || !manifest.sellers.length ||
      !Array.isArray(manifest.orders) || !manifest.orders.length)
    throw new Error("Complete supplier evidence is missing. Review required; no payment is authorized.");
  const sellerIds = new Set<string>();
  for (const seller of manifest.sellers) {
    if (!seller.sellerId || sellerIds.has(seller.sellerId)) throw new Error("Invalid or duplicate seller group.");
    sellerIds.add(seller.sellerId);
    lineTotals(seller.lines);
  }
  const ids = new Set<string>();
  let total = 0;
  for (const order of manifest.orders) {
    if (!order.orderId || ids.has(order.orderId) || !positiveMinor(order.purchaseCnyMinor))
      throw new Error("Invalid or duplicate supplier order/amount.");
    ids.add(order.orderId);
    lineTotals(order.lines);
    total += order.purchaseCnyMinor;
  }
  if (!Number.isSafeInteger(total) || total !== manifest.expectedTotalCnyMinor)
    throw new Error(`Supplier purchase total ${total} CNY-minor does not match preview ${manifest.expectedTotalCnyMinor}. Review required.`);
  if (lineTotals(manifest.sellers.flatMap(s => s.lines)) !== lineTotals(manifest.orders.flatMap(o => o.lines)))
    throw new Error("Supplier orders do not cover exactly the preview products, SKUs and quantities. Review required.");
}
export function assertFullyPaid(manifest: ProcurementManifest | undefined): asserts manifest is ProcurementManifest {
  assertCompleteManifest(manifest);
  for (const order of manifest.orders) {
    const p = order.payment;
    if (p?.state !== "Paid" || !Number.isFinite(Date.parse(p.paidAt ?? "")) ||
        !positiveMinor(p.settledAmountMinor ?? 0) || !/^[A-Z]{3}$/.test(p.settledCurrency ?? ""))
      throw new Error("Not all supplier orders have verified payment evidence. Review required.");
  }
}
export function isCompleteManifest(manifest: ProcurementManifest | undefined): boolean {
  try { assertCompleteManifest(manifest); return true; } catch { return false; }
}
export function isFullyPaid(manifest: ProcurementManifest | undefined): boolean {
  try { assertFullyPaid(manifest); return true; } catch { return false; }
}
// Payment evidence changes during reconciliation; approved identities and purchase amounts cannot.
export function manifestIdentity(manifest: ProcurementManifest): string {
  assertCompleteManifest(manifest);
  return JSON.stringify([manifest.expectedTotalCnyMinor,
    manifest.sellers.map(s => [s.sellerId, lineTotals(s.lines)]).sort(),
    manifest.orders.map(o => [o.orderId, o.purchaseCnyMinor, lineTotals(o.lines)]).sort()]);
}

export function hasVerifiedPayment(operation: { state: string; reference: string; data: OperationData } | null | undefined, reference: string, supplierId: string | undefined, contentsIdentity: string): boolean {
  return !!supplierId && operation?.reference === reference && operation.state === 'Succeeded' &&
    operation.data.kind === 'pay' && operation.data.orderContentsIdentity === contentsIdentity && operation.data.supplierId === supplierId && isFullyPaid(operation.data.manifest);
}

export function orderContentsIdentity(fields: { LineItemsJson: string; SubtotalUsd?: number; ServiceFeeUsd?: number; MarkupUsd?: number }): string {
  return JSON.stringify([fields.LineItemsJson, fields.SubtotalUsd, fields.ServiceFeeUsd, fields.MarkupUsd]);
}
